server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product
          uri: http://localhost:8090
          predicates:             
            - Path=/api/v1/product/**
        - id: courses
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/course/**
        
eureka:
  cliente:
    register-with-eureka: false
 
        